baseURL = 'https://0xl0key.github.io/'
languageCode = 'en-us'
title = 'l0key blog'
theme = "loficode"
paginate = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[params]

  customCSS = ["/css/custom.css"]

  [params.author]
    name = "Mayeul Fargier"
    image ="/images/loki.jpg"

  [params.profile]
    name = "l0key"
    tagline = "101"
    photo = "/images/loki.jpg"

  [[params.social]]
    icon = "github"
    name = "github"
    url = "https://github.com/0xl0key"

  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/mayeulfargier/"

  [[params.social]]
    icon = "discord"
    name = "discord"
    url = "https://discord.com/users/265059543799562252"

  [[menu.main]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact"
    weight = 4

[taxonomies]
  category = "blog"
  tag = "tags"
  misc = "misc"
  reverse = "reverse"
  rust = "rust"
  cpp = "cpp"
  llm = "llm"
  pwn = "pwn"
  maldev = "maldev"
